### ISSUE TITLE
What is your "time to automate" moment?

### ISSUE THREAD

**Issue by NickSeagull** [nikitavoloboev/ama#47]
First of all, thanks for all of your work, you're an inspiration! 🙏 

What is your "automation trigger"? When do you say "Hey, I need to create a hotkey/alfred workflow for this"?

**Comment by nikitavoloboev** [comment]
Thank you.

I try to automate the automating process so making new keyboard maestro macros is insanely fast for me.

ie I have macro to open `Test` macro:

![2019-08-26 at 17 29](https://user-images.githubusercontent.com/6391776/63706334-0b471b80-c827-11e9-8483-144b43797418.png)

Which I activate via karabiner by pressing tilda key + j:

![2019-08-26 at 17 29](https://user-images.githubusercontent.com/6391776/63706361-1ac66480-c827-11e9-96ba-57ace052f6af.png)

I then add actions as I like and can instantly run the `Test` macro too with karabiner:

![2019-08-26 at 17 30](https://user-images.githubusercontent.com/6391776/63706424-46e1e580-c827-11e9-8785-21118bae1145.png)

Thats keyboard maestro. Same applies to Alfred and I recently started getting into programming on a deeper level so that includes things like cli, websites etc

I have an Ideas Trello board of all the things I want to build:

https://trello.com/b/alB1ryRP

But to go back to your question.

> When do you say "Hey, I need to create a hotkey/alfred workflow for this"?

If I can do it now and its quick I do it now.

If not, I create a 2Do task with `tools` or `fix` tags and set priority (star means it needs to be addressed asap)

The king of tasks I have in `tools`

![2019-08-26 at 17 33](https://user-images.githubusercontent.com/6391776/63706543-9f18e780-c827-11e9-8bcc-5688e732bfdd.png)

And in `fix`

![2019-08-26 at 17 33](https://user-images.githubusercontent.com/6391776/63706570-af30c700-c827-11e9-9dba-a1c5972e2237.png)

Let me know if this helps.

**Comment by nikitavoloboev** [comment]
As far as what things are worth automating, thats a harder question. I try to automate things I do multiple times or try to bring multiple actions I take into 1 action (km macro, hotkey).

You learn a lot by trying to automate things, reading docs (ie vscode hotkeys, snippets etc).

**Comment by NickSeagull** [comment]
That was awesome, thank you so much! 😄
