### ISSUE TITLE
I like what you got!

### ISSUE THREAD

**Issue by ferdiptsy** [nikitavoloboev/ama#9]
Hello Voloboev,

I recently found your GitHub through the website learn anything, and I think it will help me a lot in my pursuits of education. I value looking through your open knowledge base, such as your Trello and your 'my macOS' stats (I just got a MacBook Pro) It is really fascinating to see how someone can manage their life lol. You seem to have a very complex persona, so I hope my question doesn't inhibit your busy schedule.

I have a few questions; what motivates you through all the tough work? I'm in a position where it seems hard to gain momentum. Also, how did you get started (origin story lol)? And what is your daily routine? Do you call yourself a dedicated person? That is all I have to ask, have a nice week.

**Comment by nikitavoloboev** [comment]
Hey @ferdiptsy 🙂 

Thank you for the kind words. I wrote a bit on my blog on my idea behind sharing things I am learning and things I do openly with the world [here](https://medium.com/@NikitaVoloboev/knowledge-bootstrapping-36c97e0dee19#.udmp9eotg). In many ways this article was what motivated me to create and share many of the things I share and built a strong foundation with how I approach doing and working on things.

> what motivates you through all the tough work?

I wouldn't call it tough work because I really enjoy working and sharing projects. Mostly as I build the things to solve the problems I have and it feels really great to have something working that at least partly or ideally fully solves frustration or some nagging idea you have in your head. 

> seems hard to gain momentum

I agree that it is often demotivating to work on something and see no one using or appreciating the things you've written, wrote or made. However I think the real solution to it is to enjoy the process rather than try to work only to complete a certain goal. It's much easier to focus on what you want to do this way. 

Also one advice I do have is to really not be afraid to share the things you made. There is a lot of luck involved in getting some things across to people. Just to give you an example. For Learn Anything. The whole project wouldn't exist and wouldn't have come as far as it did if it wasn't if I didn't decide to share my little mind map I made [once on Reddit](https://www.reddit.com/r/InternetIsBeautiful/comments/6a861a/interactive_mind_map_for_learning_anything/). There is no way I could of known that that post would actually get as much attention that it did if not for me posting it and seeing what happens. This works with everything in life I found. Just try and see what comes out of it. Sometimes nothing comes from it, other times something awesome can come.

> Also, how did you get started (origin story lol)

I wrote a short overview of how my 2017 year went [here](https://wiki.nikitavoloboev.xyz/looking-back/2017/2017.html) as well [an article I wrote about why I made the mind map I was working on](https://medium.com/@NikitaVoloboev/everything-connects-to-everything-else-c6a2d96a809d#.nn8gvwavn) that now became Learn Anything.

> what is your daily routine? 

In theory I have a routine I'd like myself to follow like waking up and going to sleep at the same time but in practice I sometimes have difficulty in staying true to what I want to ultimately do. Nevertheless I have [few rules](https://wiki.nikitavoloboev.xyz/productivity/flow/Rules.html) I wrote down for myself to follow which I will soon turn into Anki cards to memorise and ingrain in my memory. I can also quickly open the page to see the rules I wrote down for myself. The rules themselves are not there to limit me but to let me think less about things that I find bring no value to my life. I also share the [many lessons](https://wiki.nikitavoloboev.xyz/life/lessons-learned.html) I learned through my life. 

> Do you call yourself a dedicated person

I am dedicated to what I am passionate about. Which currently is improving my workflow and building tools to do things better and more efficiently. My passion comes from tinkering and personalising things and tools to work for me rather than just using what is provided by default. I like to customise everything to my own preference and my own workflow. I am also really passionate about building tools and experiences which I started to work on more this year. Hopefully I build something awesome I myself will love and use and can share with other people. Plus Learn Anything is only a few months old and it is only the beginning with what is possible and what can be achieved if the community comes together and builds the things and ideas they want to see in the project. 

I hope that answered some of your questions. I try to be really open about things so if you have anything more you want to ask or know. Feel free to ask. 🙂
